#此工作流使用未经GitHub认证的操作。
#它们由第三方提供，受
#单独的服务条款、隐私政策和支持
#文档

#将Jekyll站点构建和部署到GitHub页面的示例工作流
名称 :将Jekyll站点部署到页面

在 :
#针对默认分支的推送运行
推 :
分支 : [“主人” ]

#允许您从“操作”选项卡手动运行此工作流
工作流_发货 :

#设置GITHUB_TOKEN的权限以允许部署到GITHUB页面
权限 :
目录 :阅读
页 :写
id-token :写

#只允许一个并发部署，跳过正在进行的运行和最近排队的运行之间排队的运行。
#但是，不要取消正在进行的运行，因为我们希望这些生产部署能够完成。
并发 :
组 :“页面”
抵消-递增 :假

工作 :
#生成作业
建造 :
运行 :ubuntu最新
步骤 :
 -名称 :结账
使用 :行动/签出@v4
 -名称 :设置Ruby
使用 :红宝石/设置-鲁比@8575951200e472d5f2d95c625da0c7bec8217c42#v1.161.0版本
具有 :
ruby版本 : &#39;3.1&#39;#ruby版本文件不需要
集束卡 :真实的#运行“bundle-install”并自动缓存已安装的gems
缓存-版本 : zero#如果需要重新下载缓存的gems，请增加此数字
 -名称 :设置页面
身份证件 :页
使用 :行动/配置页面@v5
 -名称 :与杰基尔一起建造
#输出到“/_默认情况下，站点的目录
运行 :bundle exec jekyll构建--baseurl“${{steps.pages.outputs.base_path}}”
 环境 :
 JEKYLL_ENV公司 :生产
 -名称 :上传工件
#自动从“”上载工件/_默认情况下，站点的目录
使用 :行动/upload-pages-artifact@v3

#部署作业
部署 :
环境 :
名称 : %s读卡器
网址 : $ { {步骤.deployment.outputs.page_url } }
运行 :ubuntu最新
需要 :建造
步骤 :
 -名称 :部署到GitHub页面
        id: deployment
        uses: actions/deploy-pages@v4
